import { useEffect, useState } from 'react'
import { Alert, MenuItem, TextField } from '@mui/material'
import { useNavigate } from 'react-router-dom'
import api from '../services/api'

function Products() {
  const [products, setProducts] = useState([]); const [allProducts, setAllProducts] = useState([]); const [search, setSearch] = useState(''); const [categoryId, setCategoryId] = useState(''); const [brandId, setBrandId] = useState(''); const [error, setError] = useState(''); const navigate = useNavigate()
  useEffect(() => { api.get('/products').then((response) => { setProducts(response.data); setAllProducts(response.data) }).catch(() => setError('Unable to load products.')) }, [])
  useEffect(() => { const timer = setTimeout(() => { api.get('/products', { params: { q: search || undefined, categoryId: categoryId || undefined, brandId: brandId || undefined } }).then((response) => setProducts(response.data)).catch(() => setError('Unable to filter products.')) }, 250); return () => clearTimeout(timer) }, [search, categoryId, brandId])
  const categories = [...new Map(allProducts.filter((product) => product.category).map((product) => [product.category.id, product.category])).values()]
  const brands = [...new Map(allProducts.filter((product) => product.brand).map((product) => [product.brand.id, product.brand])).values()]
  return <section className="page-shell"><div className="page-heading"><div><span className="eyebrow">Catalog</span><h1>Products</h1><p>Search the products and services available across the vendor network.</p></div></div>{error && <Alert severity="warning" sx={{ mb: 2 }}>{error}</Alert>}<div className="toolbar"><TextField className="search-field" size="small" label="Search products or services" value={search} onChange={(event) => setSearch(event.target.value)} /><TextField select size="small" label="Category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} sx={{ minWidth: 180 }}><MenuItem value="">All categories</MenuItem>{categories.map((category) => <MenuItem value={category.id} key={category.id}>{category.categoryName}</MenuItem>)}</TextField><TextField select size="small" label="Brand" value={brandId} onChange={(event) => setBrandId(event.target.value)} sx={{ minWidth: 160 }}><MenuItem value="">All brands</MenuItem>{brands.map((brand) => <MenuItem value={brand.id} key={brand.id}>{brand.brandName}</MenuItem>)}</TextField></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Brand</th><th>Model / service</th><th>Category</th><th>Lifecycle status</th></tr></thead><tbody>{products.map((product) => <tr className="clickable" key={product.id} onClick={() => navigate(`/products/${product.id}`)}><td>{product.brand?.brandName || 'Unbranded'}</td><td className="primary-text">{product.model}</td><td>{product.category?.categoryName || 'Uncategorized'}</td><td><span className="status-pill">{product.lifecycleStatus || 'Not set'}</span></td></tr>)}{!products.length && !error && <tr><td colSpan="4"><div className="loading-state">No products match your query.</div></td></tr>}</tbody></table></div></section>
}
export default Products