import { useEffect, useState } from 'react'
import { Alert, Button, MenuItem, Paper, TextField } from '@mui/material'
import { Link, useNavigate } from 'react-router-dom'
import api from '../services/api'

function Requests() {
  const navigate = useNavigate(); const [requests, setRequests] = useState([]); const [filters, setFilters] = useState({ q: '', status: '', riskRating: '', requestType: '' }); const [error, setError] = useState(''); const { q, status, riskRating, requestType } = filters
  useEffect(() => { api.get('/requests', { params: { q, status, riskRating, requestType } }).then((response) => setRequests(response.data)).catch(() => setError('Unable to load requests.')) }, [q, status, riskRating, requestType])
  const change = (event) => setFilters({ ...filters, [event.target.name]: event.target.value })
  const openRequest = (event, requestId) => { if (event.target.closest('a, button, input, [role="combobox"]')) return; navigate(`/requests/${requestId}`) }
  return <section className="page-shell"><div className="page-heading"><div><span className="eyebrow">Single request register</span><h1>Requests</h1><p>Search, filter, export, and open every procurement request.</p></div><Button component={Link} to="/requests/new" variant="contained">New request</Button></div>{error && <Alert severity="error">{error}</Alert>}<Paper className="filter-bar" elevation={0}><TextField name="q" label="Search request, vendor, service, owner" value={filters.q} onChange={change} size="small" /><TextField select name="status" label="Status" value={filters.status} onChange={change} size="small"><MenuItem value="">All statuses</MenuItem>{['DRAFT', 'OPEN', 'IN_PROGRESS', 'AWAITING_RESPONSE', 'ON_HOLD', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'COMPLETED'].map((value) => <MenuItem value={value} key={value}>{value.replaceAll('_', ' ')}</MenuItem>)}</TextField><TextField select name="riskRating" label="Risk" value={filters.riskRating} onChange={change} size="small"><MenuItem value="">All ratings</MenuItem>{['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'UNASSIGNED'].map((value) => <MenuItem value={value} key={value}>{value}</MenuItem>)}</TextField><Button href="http://localhost:5002/api/requests/export" variant="outlined">Export CSV</Button></Paper><div className="table-wrap"><table className="data-table"><thead><tr><th>Request ID</th><th>Vendor</th><th>Category service type</th><th>Owner</th><th>Type</th><th>Risk</th><th>Stage</th><th>Status</th><th>Reviews</th><th>Next action</th></tr></thead><tbody>{requests.map((request) => <tr className="clickable" tabIndex="0" onClick={(event) => openRequest(event, request.id)} onKeyDown={(event) => { if (event.key === 'Enter') navigate(`/requests/${request.id}`) }} key={request.id}><td><Link className="table-link" to={`/requests/${request.id}`}>{request.requestNumber}</Link></td><td>{request.vendorName || 'Not specified'}</td><td>{request.categoryServiceType || 'Not specified'}</td><td>{request.businessOwner || request.requestedBy}</td><td>{request.requestType || 'Not specified'}</td><td>{request.riskRating}</td><td>{request.currentStage || 'Not set'}</td><td><span className="status-pill">{request.status.replaceAll('_', ' ')}</span></td><td>{request.outstandingReviews} outstanding</td><td>{request.currentAction || 'No action recorded'}</td></tr>)}{!requests.length && <tr><td colSpan="10"><div className="empty-state">No requests found.</div></td></tr>}</tbody></table></div></section>
}

export default Requests
