import { useEffect, useState } from 'react'
import { Alert, Paper } from '@mui/material'
import { Link, useParams } from 'react-router-dom'
import api from '../services/api'

function RFQDetails() {
  const { id } = useParams(); const [rfq, setRfq] = useState(null); const [error, setError] = useState('')
  useEffect(() => { api.get(`/rfqs/${id}`).then((response) => setRfq(response.data)).catch(() => setError('Unable to load this RFQ.')) }, [id])
  if (error) return <section className="page-shell"><Alert severity="error">{error}</Alert></section>
  if (!rfq) return <section className="page-shell"><div className="loading-state">Loading RFQ...</div></section>
  return <section className="page-shell"><div className="detail-top"><div><Link className="back-link" to="/rfqs">← All RFQs</Link><h1>{rfq.rfqNumber}</h1><p>{rfq.status} · Requested by {rfq.requestedBy}</p></div></div><div className="detail-grid"><Paper elevation={0} className="section-band"><h2>RFQ summary</h2><dl className="info-list"><div><dt>Request date</dt><dd>{new Date(rfq.requestDate).toLocaleDateString()}</dd></div><div><dt>Closing date</dt><dd>{rfq.closingDate ? new Date(rfq.closingDate).toLocaleDateString() : 'Not set'}</dd></div><div><dt>Category</dt><dd>{rfq.category?.categoryName || 'Not specified'}</dd></div><div><dt>Requested by</dt><dd>{rfq.requestedBy}</dd></div></dl><p style={{ marginTop: 22 }}>{rfq.businessJustification || 'No business justification provided.'}</p></Paper><Paper elevation={0} className="section-band"><h2>Invited vendors</h2><p>{rfq.vendors.length} supplier{rfq.vendors.length === 1 ? '' : 's'} invited</p>{rfq.vendors.length ? rfq.vendors.map((entry) => <div key={entry.id} style={{ padding: '11px 0', borderTop: '1px solid #edf2f0' }}><strong>{entry.vendor.vendorName}</strong><span className="sub-text">{entry.responseStatus}</span></div>) : <div className="empty-state">No vendors invited.</div>}</Paper></div><div className="detail-grid"><Paper elevation={0} className="section-band"><h2>Requested items</h2><p>{rfq.items.length} item{rfq.items.length === 1 ? '' : 's'}</p>{rfq.items.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Quantity</th><th>Delivery date</th></tr></thead><tbody>{rfq.items.map((item) => <tr key={item.id}><td className="primary-text">{item.product?.model || 'Product not specified'}</td><td>{item.quantity}</td><td>{item.targetDeliveryDate ? new Date(item.targetDeliveryDate).toLocaleDateString() : '—'}</td></tr>)}</tbody></table></div> : <div className="empty-state">No items added.</div>}</Paper><Paper elevation={0} className="section-band"><h2>Submitted quotes</h2><p>{rfq.quotes.length} quote{rfq.quotes.length === 1 ? '' : 's'} received</p>{rfq.quotes.length ? rfq.quotes.map((quote) => <div key={quote.id} style={{ padding: '11px 0', borderTop: '1px solid #edf2f0' }}><strong>{quote.vendor.vendorName}</strong><span className="sub-text">{quote.currency} {quote.unitPrice} · {quote.product.model}</span></div>) : <div className="empty-state">No quotes submitted.</div>}</Paper></div></section>
}
export default RFQDetails