import { useEffect, useState } from 'react'
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, TextField } from '@mui/material'
import api from '../services/api'

const initialForm = { vendorName: '', vendorType: '', country: '', riskRating: '', currency: 'USD' }

function Vendors() {
  const [vendors, setVendors] = useState([]); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false); const [form, setForm] = useState(initialForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const fetchVendors = () => api.get('/vendors').then((response) => setVendors(response.data)).catch(() => setError('Unable to load vendors.')).finally(() => setLoading(false))
  const loadVendors = () => { setLoading(true); fetchVendors() }
  useEffect(() => { fetchVendors() }, [])
  const filtered = vendors.filter((vendor) => `${vendor.vendorName} ${vendor.vendorType || ''} ${vendor.country || ''}`.toLowerCase().includes(search.toLowerCase()))
  const updateField = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const submit = (event) => { event.preventDefault(); setSaving(true); api.post('/vendors', form).then(() => { setOpen(false); setForm(initialForm); loadVendors() }).catch(() => setError('Unable to save this vendor.')).finally(() => setSaving(false)) }
  return <section className="page-shell"><div className="page-heading"><div><span className="eyebrow">Supplier directory</span><h1>Vendors</h1><p>Manage the organizations your procurement team works with.</p></div><Button variant="contained" onClick={() => setOpen(true)}>Add vendor</Button></div>{error && <Alert severity="warning" onClose={() => setError('')} sx={{ mb: 2 }}>{error}</Alert>}<div className="toolbar"><TextField className="search-field" size="small" label="Search vendors" value={search} onChange={(event) => setSearch(event.target.value)} /></div>{loading ? <div className="loading-state">Loading vendors...</div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Vendor name</th><th>Vendor type</th><th>Country</th><th>Risk rating</th><th>Status</th><th>Currency</th></tr></thead><tbody>{filtered.map((vendor) => <tr className="clickable" key={vendor.id} onClick={() => { window.location.href = `/vendors/${vendor.id}` }}><td><span className="primary-text">{vendor.vendorName}</span><span className="sub-text">Vendor #{vendor.id}</span></td><td>{vendor.vendorType || '—'}</td><td>{vendor.country || '—'}</td><td><Pill value={vendor.riskRating} warning={vendor.riskRating === 'MEDIUM'} /></td><td><Pill value={vendor.status} /></td><td>{vendor.currency || '—'}</td></tr>)}{!filtered.length && <tr><td colSpan="6"><div className="loading-state">No vendors match this search.</div></td></tr>}</tbody></table></div>}<Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><form onSubmit={submit}><DialogTitle>Add vendor</DialogTitle><DialogContent><TextField autoFocus required margin="dense" name="vendorName" label="Vendor name" value={form.vendorName} onChange={updateField} fullWidth /><TextField margin="dense" name="vendorType" label="Vendor type" value={form.vendorType} onChange={updateField} fullWidth /><TextField margin="dense" name="country" label="Country" value={form.country} onChange={updateField} fullWidth /><TextField select margin="dense" name="riskRating" label="Risk rating" value={form.riskRating} onChange={updateField} fullWidth><MenuItem value="LOW">Low</MenuItem><MenuItem value="MEDIUM">Medium</MenuItem><MenuItem value="HIGH">High</MenuItem></TextField><TextField margin="dense" name="currency" label="Currency" value={form.currency} onChange={updateField} fullWidth /></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? 'Saving...' : 'Save vendor'}</Button></DialogActions></form></Dialog></section>
}
function Pill({ value, warning }) { return <span className={`status-pill${warning ? ' warning' : !value ? ' neutral' : ''}`}>{value || 'Not rated'}</span> }
export default Vendors