import { useEffect, useState } from 'react'
import { Alert, Box, Paper, Tab, Tabs } from '@mui/material'
import { Link, useParams } from 'react-router-dom'
import api from '../services/api'

function VendorDetails() {
  const { id } = useParams(); const [vendor, setVendor] = useState(null); const [tab, setTab] = useState(0); const [error, setError] = useState('')
  useEffect(() => { api.get(`/vendors/${id}`).then((response) => setVendor(response.data)).catch(() => setError('Unable to load this vendor.')) }, [id])
  if (error) return <section className="page-shell"><Alert severity="error">{error}</Alert></section>
  if (!vendor) return <section className="page-shell"><div className="loading-state">Loading vendor...</div></section>
  return <section className="page-shell"><div className="detail-top"><div><Link className="back-link" to="/vendors">← All vendors</Link><h1>{vendor.vendorName}</h1><p>{vendor.vendorType || 'Vendor'} · {vendor.country || 'Country not specified'}</p></div></div><Paper elevation={0} className="section-band"><Tabs value={tab} onChange={(_, value) => setTab(value)} aria-label="Vendor details"><Tab label="Overview" /><Tab label={`Contacts (${vendor.contacts.length})`} /><Tab label={`Products (${vendor.vendorProducts.length})`} /><Tab label={`Contracts (${vendor.contracts.length})`} /></Tabs><Box sx={{ pt: 3 }}>{tab === 0 && <Overview vendor={vendor} />}{tab === 1 && <Contacts contacts={vendor.contacts} />}{tab === 2 && <Products products={vendor.vendorProducts} />}{tab === 3 && <Contracts contracts={vendor.contracts} />}</Box></Paper></section>
}
function Overview({ vendor }) { return <dl className="info-list"><div><dt>Status</dt><dd>{vendor.status}</dd></div><div><dt>Risk rating</dt><dd>{vendor.riskRating || 'Not rated'}</dd></div><div><dt>Currency</dt><dd>{vendor.currency || 'Not specified'}</dd></div><div><dt>Payment terms</dt><dd>{vendor.paymentTerms || 'Not specified'}</dd></div><div><dt>Website</dt><dd>{vendor.website || 'Not specified'}</dd></div><div><dt>ERP vendor code</dt><dd>{vendor.erpVendorCode || 'Not specified'}</dd></div></dl> }
function Contacts({ contacts }) { return contacts.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Role</th><th>Email</th><th>Phone</th></tr></thead><tbody>{contacts.map((contact) => <tr key={contact.id}><td className="primary-text">{contact.name}</td><td>{contact.role || '—'}</td><td>{contact.email || '—'}</td><td>{contact.phone || '—'}</td></tr>)}</tbody></table></div> : <div className="empty-state">No contacts added.</div> }
function Products({ products }) { return products.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Lead time</th><th>Warranty</th><th>Reseller</th></tr></thead><tbody>{products.map(({ id, product, leadTimeDays, warrantyMonths, authorisedReseller }) => <tr key={id}><td className="primary-text">{product.model}</td><td>{leadTimeDays ? `${leadTimeDays} days` : '—'}</td><td>{warrantyMonths ? `${warrantyMonths} months` : '—'}</td><td>{authorisedReseller ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div> : <div className="empty-state">No products mapped.</div> }
function Contracts({ contracts }) { return contracts.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Contract</th><th>Dates</th><th>Status</th><th>Value</th></tr></thead><tbody>{contracts.map((contract) => <tr key={contract.id}><td className="primary-text">{contract.contractNumber}</td><td>{new Date(contract.startDate).toLocaleDateString()} – {new Date(contract.endDate).toLocaleDateString()}</td><td>{contract.status}</td><td>{contract.currency} {contract.totalValue}</td></tr>)}</tbody></table></div> : <div className="empty-state">No contracts added.</div> }
export default VendorDetails